### ISSUE TITLE
Font infos

### ISSUE THREAD

**Issue by emmamarichal** [googlefonts/dynapuff#2]
Hello @davelab6 @Tosche,

I'm working on the DynaPuff font, and I'm wondering what do you want to see in the font infos (creation date, designer, designer url, manufacturer, copyright date, etc. -> see screenshot). 
Same question for authors.txt, contributors.txt, and readme.md, tell me if there is any particular information you want to include in.

This is what I have for now:
<img width="953" alt="Fontinfos" src="https://user-images.githubusercontent.com/64773544/167137247-068ad0c9-11a1-41aa-993d-c5026dd54583.png">

Thanks!

**Comment by davelab6** [comment]
* Family Name: `DynaPuff`

This needs adding to the FontBakery Google Fonts profile's list of camelcase names.

* Version: `2.000`

Since this is extended glyph set from the first internal release

* Designer: `Toshi Omagari, Jennifer Daniel`
* Designer URL: `https://tosche.net`
* Manufacturer: `Google Fonts`
* Manufacturer URL: `https://github.com/googlefonts/dynapuff`
* Copyright: `Copyright 2021 The DynaPuff Project Authors (https://github.com/googlefonts/dynapuff)`
* License: As is
* License URL: As is
* Trademark: None
* Vendor ID: `GOOG`

**Comment by emmamarichal** [comment]
Perfect, thank you :)
